---
title: "Personalities Explored: A Data Exploration of My Girlfriend's and My Spotify Top 50 Songs"
author: "Ding Si Han | Spring 2022"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    theme: journal
    self_contained: false
    vertical_layout: fill
---
```{r setup, include=FALSE}
library(flexdashboard)
library(ggrepel)
library(ggthemes)
library(tidyverse)
library(compmus)
library(gridExtra)
library(spotifyr)
library(plotly)

sihan_df <- read.csv(file="../data/sihan.csv")
megan_df <- read.csv(file="../data/megan.csv")

combined_df <- rbind(sihan_df, megan_df)
combined_df$mode <- as.factor(combined_df$mode)
summary(combined_df)

# Megan's Songs
song_black_bear <- "2BuMmK2Yguu6vQf1PJ2xQu"
song_maybe <- "5tOUTNlLFd5u5xPt3unOVp"
song_carry_you <- "0u4rkpmNtgcFxYHepnVF4v"

# Si Han's Songs
song_yet_not_i <- "439tGS9rVbyTjj5SmneD56"
song_ta_shuo <- "632VyMrvhsHIsO4zq9khts"
song_cornerstone <- "23STcG7v9HNwdqnROFSS8n"
```

```{r}

library(ggdendro)
library(tidymodels)
library(heatmaply) 

library(compmus)

get_conf_mat <- function(fit) {
  outcome <- .get_tune_outcome_names(fit)
  fit %>% 
    collect_predictions() %>% 
    conf_mat(truth = outcome, estimate = .pred_class)
}  

get_pr <- function(fit) {
  fit %>% 
    conf_mat_resampled() %>% 
    group_by(Prediction) %>% mutate(precision = Freq / sum(Freq)) %>% 
    group_by(Truth) %>% mutate(recall = Freq / sum(Freq)) %>% 
    ungroup() %>% filter(Prediction == Truth) %>% 
    select(class = Prediction, precision, recall)
}  




megan <- 
  get_playlist_audio_features("spotify", "5ZSKhsr61NNYIpWPjLfFCV")
sihan <- get_playlist_audio_features("spotify", "0dvRhGMEoCG9s8WA3ATLYd")
indie <-
  bind_rows(
    megan %>% mutate(playlist = "Megan") %>% slice_head(n = 50),
    sihan %>% mutate(playlist = "Si Han") %>% slice_head(n = 50)
  ) 





indie_features <-
  indie %>%  # For your portfolio, change this to the name of your corpus.
  add_audio_analysis() %>% 
  mutate(
    playlist = factor(playlist),
    segments = map2(segments, key, compmus_c_transpose),
    pitches =
      map(
        segments,
        compmus_summarise, pitches,
        method = "mean", norm = "manhattan"
      ),
    timbre =
      map(
        segments,
        compmus_summarise, timbre,
        method = "mean",
      )
  ) %>%
  mutate(pitches = map(pitches, compmus_normalise, "clr")) %>%
  mutate_at(vars(pitches, timbre), map, bind_rows) %>%
  unnest(cols = c(pitches, timbre))







indie_recipe <-
  recipe(
    playlist ~
      danceability +
      energy +
      loudness +
      speechiness +
      acousticness +
      instrumentalness +
      liveness +
      valence +
      tempo +
      duration +
      C + `C#|Db` + D + `D#|Eb` +
      E + `F` + `F#|Gb` + G +
      `G#|Ab` + A + `A#|Bb` + B +
      c01 + c02 + c03 + c04 + c05 + c06 +
      c07 + c08 + c09 + c10 + c11 + c12,
    data = indie_features,          # Use the same name as the previous block.
  ) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors())      # Converts to z-scores.





indie_cv <- indie_features %>% vfold_cv(5)



knn_model <-
  nearest_neighbor(neighbors = 1) %>%
  set_mode("classification") %>% 
  set_engine("kknn")
indie_knn <- 
  workflow() %>% 
  add_recipe(indie_recipe) %>% 
  add_model(knn_model) %>% 
  fit_resamples(
    indie_cv, 
    control = control_resamples(save_pred = TRUE)
  )


indie_knn %>% get_conf_mat()



indie_knn %>% get_conf_mat() %>% autoplot(type = "mosaic")
indie_knn %>% get_conf_mat() %>% autoplot(type = "heatmap")
indie_knn %>% get_pr()


```



# Random Forest
```{r}
forest_model <-
  rand_forest() %>%
  set_mode("classification") %>% 
  set_engine("ranger", importance = "impurity")
indie_forest <- 
  workflow() %>% 
  add_recipe(indie_recipe) %>% 
  add_model(forest_model) %>% 
  fit_resamples(
    indie_cv, 
    control = control_resamples(save_pred = TRUE)
  )

indie_forest %>% get_pr()

workflow() %>% 
  add_recipe(indie_recipe) %>% 
  add_model(forest_model) %>% 
  fit(indie_features) %>% 
  pluck("fit", "fit", "fit") %>%
  ranger::importance() %>% 
  enframe() %>% 
  mutate(name = fct_reorder(name, value)) %>% 
  ggplot(aes(name, value)) + 
  geom_col() + 
  coord_flip() +
  theme_minimal() +
  labs(x = NULL, y = "Importance")

```


```{r}
indie_features %>%
  ggplot(aes(x = instrumentalness, y = duration, colour = playlist, size = energy)) +
  geom_point(alpha = 0.8) +
  scale_color_viridis_d() +
  labs(
    x = "Instrumentalness",
    y = "Duration",
    size = "Energy",
    colour = "Playlist"
  )
```