
```{r, eval = FALSE}
remotes::install_github('jaburgoyne/compmus')
```

```{r, setup}
library(tidyverse)
library(spotifyr)
library(compmus)
```


```{r}
light_rain = "439tGS9rVbyTjj5SmneD56"
yet_not_i = "439tGS9rVbyTjj5SmneD56"
shuo_hao_bu_ku = "56wVfJKtnwlSZtC4NVgIrf"

wood <-
  get_tidy_audio_analysis(shuo_hao_bu_ku) %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)

wood %>%
  mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```


```{r}
## The Tallis Scholars
tallis <-
  get_tidy_audio_analysis("2J3Mmybwue0jyQ0UVMYurH") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)
## La Chapelle Royale
chapelle <-
  get_tidy_audio_analysis("4ccw2IcnFt1Jv9LqQCOYDi") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)

compmus_long_distance(
  tallis %>% mutate(pitches = map(pitches, compmus_normalise, "chebyshev")),
  chapelle %>% mutate(pitches = map(pitches, compmus_normalise, "chebyshev")),
  feature = pitches,
  method = "euclidean"
) %>%
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_equal() +
  labs(x = "The Tallis Scholars", y = "La Chapelle Royale") +
  theme_minimal() +
  scale_fill_viridis_c(guide = NULL)
```
